## Runtime Dependencies: MUST RUN FIRST!

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

# ### Bonus: Multiple Outputs Per Cell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Module 4: NumPy

**Importing NumPy:**

```python
import numpy as np
```

NumPy is an essential Python library that adds the ability to create arrays in Python, along with many other features.

What are arrays?

Arrays are a specialized list that stores a homogeneous data type, like float64 or strings, that is compacted into memory—making operations across the array considerably faster.

Leveraging arrays over lists can leverage coding speed ups of anywhere from 5 to 100x faster for routine operations!

On top of that, NumPy also brings countless matrix and linear algebra operations, and has robust statistical applications too.

For reference, NumPy's community guide is over 1800 pages long: https://numpy.org/doc/stable/numpy-ref.pdf



## Module 4.1: Math Review

### Scalars, Vectors, and Matricies

There are 3 essential linear algebra concepts to keep consistent:

| Type | Scalars | Vectors | Matricies |
| --- | --- | --- | --- |
| **Description** | Are a single number | 1D Array of Numbers (Horizontal or Vertical) | 1D/2D Array of Numbers |
| **Representation** | $$\begin{matrix} 1 \end{matrix}$$ | $$\begin{bmatrix} 1 & 2 & 3 \end{bmatrix}$$  $$\begin{bmatrix} 1  \\ 2  \\ 3 \end{bmatrix}$$| $$\begin{bmatrix} 1 & 2 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$ |

Note: All Vectors are Matricies, but not all Matricies are Vectors!

### Scalar Multiplication of Matricies

If $M = [m_{i,j}]$ is a matrix and *k* is a scalar...

$$M*k = kM = [km_{i,j}]$$

$$5 * \begin{bmatrix} 1 & 3 & 2 \\ 7 & -2 & 4 \end{bmatrix} = \begin{bmatrix} 5*1 & 5*3 & 5*2 \\ 5*7 & 5*-2 & 5*4 \end{bmatrix} = \begin{bmatrix} 5 & 15 & 10 \\ 35 & -10 & 20 \end{bmatrix}$$

### Matrix - Vector Multiplication

Let $M = [m_{i,j}]$ be a matrix of dimensions $i * j$ and $v = [v_{j}]$ be a vector of length $j$.

Below is an example of how to multiply $M * v$:

$$Mv = \begin{bmatrix} 1 & 4 & 2 \\ 3 & 2 & 1 \end{bmatrix} * \begin{bmatrix} 2 \\ 1 \\ 4 \end{bmatrix} = \begin{bmatrix} a \\ b\end{bmatrix}$$

Let's calculate the first answer $a$:

$$Mv = \begin{bmatrix} \color{red}{\text{1}} & \color{yellow}{\text{4}} & \color{orange}{\text{2}} \\ 3 & 2 & 1 \end{bmatrix} * \begin{bmatrix} \color{red}{\text{2}} \\ \color{yellow}{\text{1}} \\ \color{orange}{\text{4}} \end{bmatrix} = \begin{bmatrix} \color{red}{\text{(1*2)}} +
\color{yellow}{\text{(4*1)}} +
\color{orange}{\text{(2*4)}} \\ b\end{bmatrix} = \begin{bmatrix} 14 \\ b\end{bmatrix}$$

And now let's calculate the second answer $b$:

$$Mv = \begin{bmatrix} 1 & 4 & 2 \\ \color{red}{\text{3}} & \color{yellow}{\text{2}} & \color{orange}{\text{1}} \end{bmatrix} * \begin{bmatrix} \color{red}{\text{2}} \\ \color{yellow}{\text{1}} \\ \color{orange}{\text{4}} \end{bmatrix} = \begin{bmatrix} 14 \\ \color{red}{\text{(3*2)}} +
\color{yellow}{\text{(2*1)}} +
\color{orange}{\text{(1*4)}} \end{bmatrix} = \begin{bmatrix} 14 \\ 12\end{bmatrix}$$

### Matrix - Matrix Multiplication

To multiply matricies together, the inner dimensions must be the same!

Let $M_0$ be a matrix with dimensions $i * j$ and $M_1$ be a matrix with dimensions $j * k$. The resulting matrix will have dimensions $i * k$.

For example, let's multiply matrix $M_0$ with dimensions $(2 * 3)$ and matrix $M_1$ with dimensions $(3 * 2)$. The resulting matrix will have dimensions $(2 * 2)$.

$$M_0M_1 = \begin{bmatrix} 4&2&6 \\ 2 & 1 & 2\end{bmatrix} * 
\begin{bmatrix}
4 & 3 \\
2 & 1 \\
3 & 5
\end{bmatrix} = 
\begin{bmatrix}
a & b \\
c & d
\end{bmatrix}
$$

Let's calculate the first row for $a$ and $b$:

$$M_0M_1 = \begin{bmatrix} \color{red}{4} & \color{yellow}{2} & \color{orange}{6} \\ 2 & 1 & 2\end{bmatrix} * 
\begin{bmatrix}
\color{blue}{4} & \color{green}{3} \\
\color{purple}{2} & \color{teal}{1} \\
\color{gold}{3} & \color{violet}{5}
\end{bmatrix} =
\begin{bmatrix}
\color{red}{4}\color{blue}{(4)} + 
\color{yellow}{2}\color{purple}{(2)} +
\color{orange}{6}\color{gold}{(3)} &
\color{red}{4}\color{green}{(3)} +
\color{yellow}{2}\color{teal}{(1)} +
\color{orange}{6}\color{violet}{(5)} \\
c & d
\end{bmatrix} =
\begin{bmatrix}
38 & 44 \\
c & d
\end{bmatrix}$$

And now calculate the second row for $c$ and $d$:

$$M_0M_1 = \begin{bmatrix} 4&2&6 \\ \color{red}{2} & \color{yellow}{1} & \color{orange}{2}\end{bmatrix} * 
\begin{bmatrix}
\color{blue}{4} & \color{green}{3} \\
\color{purple}{2} & \color{teal}{1} \\
\color{gold}{3} & \color{violet}{5}
\end{bmatrix} =
\begin{bmatrix}
38 & 44 \\
\color{red}{2}\color{blue}{(4)} + 
\color{yellow}{1}\color{purple}{(2)} +
\color{orange}{2}\color{gold}{(3)} &
\color{red}{2}\color{green}{(3)} +
\color{yellow}{1}\color{teal}{(1)} +
\color{orange}{2}\color{violet}{(5)}
\end{bmatrix} =
\begin{bmatrix}
38 & 44 \\
16 & 17
\end{bmatrix}$$

## Module 4.2: 1-Dimensional Arrays in NumPy

In Python, we have a few options for generating arrays in NumPy:

1. From a Python List
2. From a CSV file
3. Range of Numbers / Integers
4. Array of Constants (Ones, Zeros, Etc.)

### Generating 1D Array From List

Let's say we have the following list:

```python
lst = [0,1,2,3,4,5,6,7,8,9]
```

We can generate a 1D array by passing the list into the `np.array()` function!

Let's look at the example below, notice how outputs are different!

*Note: Common shorthands for list is lst and array, arr.

In [2]:
lst = [0,1,2,3,4,5,6,7,8,9]
arr = np.array(lst)

lst
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Fetching Data From Git

To fetch data from Git, we just need the raw data link:

https://raw.githubusercontent.com/mhall-simon/sdac-training/main/data/arr-1D-test-scores.csv

*For some reason, this single column CSV from GitHub isn't being loaded properly. Not certain why. Exact file in Dropbox & AWS loads properly.*

### Fetching Data From Dropbox Note

When you grab the Dropbox link for a file, it includes the URL argument *dl=0*, which means Download = False!

https://www.dropbox.com/s/jlux8ltmhw8qg4b/arr-1D-test-scores.csv?dl=0

This link takes us to the Dropbox file preview, and not the file directly. To get around this, just change the dropbox link at the end to have *dl=1*:

https://www.dropbox.com/s/jlux8ltmhw8qg4b/arr-1D-test-scores.csv?dl=1

### Fetching Data From Working Directory

If a file is in our working directory, we just need to have the relative path copied:

arr-1D-test-scores.csv

If we want to target a specific file on our Computer, you need to specify an absolute path:

Mac:
/Users/matthall/Documents/Data/arr-1D-test-scores.csv

Windows:
C:\Users\matth\OneDrive\Documents\Data\arr-1D-test.scores.csv

Keep in mind, when sharing a project, linking to an online source is the easiest, followed by relative pathing. Absolute paths won't work on someone else's computer!!

### Generating Array From CSV File

To use the `np.genfromtxt()` function, we need 3 things:

1. The path (location) of the file first
2. The delimiter format, usually `,`
3. Header rows to skip (it's always recommended to have one header row in your CSV to reduce errors)

General Data Science Tip: Always download your data and inspect it in Excel! Don't work blind.

We're going to use `skip_header=1` because the file looks like this in Excel:

| | **A** |
| --- | --- |
| **1** | stats_final |
| **2** | 90 |
| **3** | 50 |
| ... | ... |
| **51** | 85 |

Let's import our first data set!

In [3]:
target_url = "https://www.dropbox.com/s/jlux8ltmhw8qg4b/arr-1D-test-scores.csv?dl=1"

arr = np.genfromtxt(target_url, delimiter=',', skip_header=1)

arr

array([90., 50., 71., 70., 59., 63., 87., 70., 77., 43., 93., 65., 42.,
       79., 62., 64., 66., 60., 73., 67., 56., 42., 96., 73., 73., 74.,
       99., 41., 90., 48., 72., 56., 92., 43., 60., 57., 60., 65., 53.,
       88., 86., 59., 40., 88., 43., 84., 88., 97., 48., 85.])

### Generating Array From Range of Numbers


We can pass the `range()` function of Python into NumPy to generate an Array!

Examples of the range function:

`range(100)`: Generates range of integers 0 through 99

`range(10,20)` Generates range of integers 10 through 19

`range(-10,11,2)` Generates range of integers -10 through 10, with an interval of 2

In [4]:
arr = np.array(range(100))
arr

arr = np.array(range(10,20))
arr

arr = np.array(range(-10,11,2))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10])

### Generating Array Of Zeroes, Ones, Constants

Sometimes, we want to generate an array of constant values and not just a range.

These can be used as weights or even a placeholder for future data.

For constants, I'm using a trick to generate equal weights across an array for length n. This is a sneak peek at broadcasting!

In [5]:
arr = np.zeros(10)
arr

arr = np.ones(10)
arr

n = 20
arr = np.ones(n)/n
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05,
       0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05])

## Module 4.3: 2-Dimensional Arrays in NumPy

### Generating 2D Array From Python List

A 2D array is essentially a matrix too! Otherwise, it can be a structure for tabular data!

Let's generate one from a nested Python list:

In [6]:
lst = [[0,1,2],[3,4,5],[6,7,8]]

arr = np.array(lst)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Generating 2D Matrix with Range

Note: Need to use a range and shape that properly map, and `.reshape()` arguments are a tuple of `(rows,cols)`.

$i = m * n$

```python
np.array(range(i)).reshape((m,n))
```

In [7]:
matrix = np.array(range(36)).reshape((3,12))
matrix

matrix = np.array(range(16)).reshape((4,4))
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Generating 2D Matrix with Constants

Similar to above, we just need to reshape with proper dimensions.

In [8]:
matrix = np.zeros(25).reshape((5,5))
matrix

matrix = np.ones(24).reshape((4,6))
matrix

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

### Generating 2D Array from File

We can also import a 2D array from a csv file, same as above.

To make sense of this array, we need to go to the link: https://github.com/mhall-simon/sdac-training/blob/main/data/arr-2D-test-scores.csv

If you're thinking column and row information would be useful, you'd be correct, but that comes with Pandas' DataFrame.

In [9]:
target_url = "https://raw.githubusercontent.com/mhall-simon/sdac-training/main/data/arr-2D-test-scores.csv"

arr = np.genfromtxt(target_url, delimiter=',', skip_header=1)

arr

array([[ 8.,  9.,  5., 89., 96.],
       [ 7.,  5.,  7., 91., 99.],
       [10.,  8.,  4., 77., 87.],
       [ 9.,  7.,  5., 80., 66.],
       [ 5.,  9.,  8., 88., 90.]])

## Module 4.4: Indexing Arrays

### Indexing 1D Arrays

1D arrays are indexed the same as a Python list!

We can access a single point, a range, and use negative indexing too!

In [10]:
arr = np.array(range(10))

arr[5]

arr[2:6]

arr[-1]

5

array([2, 3, 4, 5])

9

### Indexing 2D Arrays

2D arrays are indexed slightly different, as we need to worry about both rows and columns!

For a single point, we're going to access it using the syntax `arr[row,col]`, and remember both rows and columns are zero indexed too!

For a single row, we're going to access it using the syntax `arr[row,:]`

For a single column, we're going to access it using the syntax `arr[:,col]`

And we can even slice a matrix / vector subset with `arr[row:row,col:col]`

*Note: Remember Python is always zero-indexed and slicing is inclusive-exclusive*

In [11]:
matrix = np.array(range(100)).reshape((10,10))

matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [12]:
matrix[3,4]

matrix[4,:]

matrix[:,7]

matrix[2:5,4:9]

34

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

array([[24, 25, 26, 27, 28],
       [34, 35, 36, 37, 38],
       [44, 45, 46, 47, 48]])

## Module 4.5: Attributes, Methods, & Statistical Moments of Arrays

### Useful Array Attributes

| Attribute | Description |
| :---: | --- |
| `.dtype` | Data type of the arrays' elements |
| `.size` | Number of elements in the array |
| `.shape` | Tuple of array dimensions |
| `.ndim` | Number of array dimensions |
| `.T` | Transposed array |

In [13]:
arr = np.array(range(12)).reshape((3,4))

arr

arr.dtype
arr.size
arr.shape
arr.ndim
arr.T

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

dtype('int64')

12

(3, 4)

2

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [14]:
arr = np.array(range(12))

arr.dtype
arr.size
arr.shape
arr.ndim

dtype('int64')

12

(12,)

1

### Useful Array Methods

| Method | Description |
| :---: | --- |
| `.astype()` | Copy of the array, cast to a specified type. |
| `.clip()` | Return an array whole values are limited to [min, max] |
| `.copy()` | Return copy of array |
| `.diagonal()` | Returns specified diagonal of array |
| `.round()` | Returns array rounded to precision level |
| `.sort()` | Sorts an array in place |


#### Cast to Data Type & Boundaries

In [15]:
# 5 by 5 Matrix
arr = np.array(range(25)).reshape((5,5))

arr.astype(float)

arr.clip(min=5, max=20)

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

array([[ 5,  5,  5,  5,  5],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 20, 20, 20, 20]])

#### Copying Array and Modifying Original

In [16]:
arr = np.array(range(5))

arr2 = arr.copy()

arr*=0

arr
arr2

array([0, 0, 0, 0, 0])

array([0, 1, 2, 3, 4])

#### Diagonal of Array

In [17]:
arr = np.array(range(25)).reshape((5,5))

arr
arr.diagonal()

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([ 0,  6, 12, 18, 24])

#### Roudning Array to Precision Level

In [18]:
arr = np.ones(10)/9

arr
arr.round(3)

array([0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
       0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111])

array([0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111, 0.111,
       0.111])

#### Sorting Array

In [19]:
arr = np.array([5,-3,3,7,-5,1,-1,-7])

arr.sort()
arr

array([-7, -5, -3, -1,  1,  3,  5,  7])

### Statistical Moments & Sum/Product of Arrays

| Method | Statistical Moment / Description |
| :---: | --- |
| `.mean()` | Statistical mean of array |
| `.var()` | Variance of array |
| `.std()` | Standard deviation of array |
| `.max()` | Maximum value of array |
| `.min()` | Minimum value of array |
| `.sum()` | Summation of all elements |
| `.prod()` | Product of all elements |
| `.cumsum()` | Array transformed into rolling cumulative sum |
| `.cumprod()` | Array transformed into rolling cumulative product |


#### Mean, Variance, Standard Deviation, Min, Max

In [20]:
# ### Generates Random Array of Numbers
from numpy.random import default_rng
rng = default_rng()
# ### Covered in Module 4.9 in Depth (Ignore for Now)

# This code takes 100 samples from a standard normal distribution, mean = 0, std = 1
arr = rng.standard_normal(100)

arr.mean()

arr.var()
arr.std()

arr.max()
arr.min()

-0.010504275299620136

1.1556168732278334

1.0749962200993235

3.160711128215966

-2.5606066042089015

#### Sum & Cumulative Sum

In [21]:
arr = np.array(range(10))

arr.sum()

arr.cumsum()

45

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

#### Product & Cumulative Product

In [22]:
arr = np.ones(10)*2

arr.prod()
arr.cumprod()

1024.0

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

## Module 4.6: Manipulating Arrays: Broadcasting Scalars

Earlier, in the Math Review, I provided an example of a scalar - matrix multiplication, where each element was multiplied by the scalar.

With NumPy, this is really easy, and we can actually use any operator for broadcasting! (It's not limited to matricies.)

It's known as broadcasting because it's a one-to-many operation, just like a radio tower broadcasting music.

**Broadcasting is much faster than iterating through a Python list with a for loop or list comprehension.**

### Broadcasting Multiplication and Division

In [23]:
arr = np.array(range(36)).reshape((6,6))

arr*2

arr/2

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46],
       [48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70]])

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5,  5. ,  5.5],
       [ 6. ,  6.5,  7. ,  7.5,  8. ,  8.5],
       [ 9. ,  9.5, 10. , 10.5, 11. , 11.5],
       [12. , 12.5, 13. , 13.5, 14. , 14.5],
       [15. , 15.5, 16. , 16.5, 17. , 17.5]])

### Broadcasting Addition and Subtraction

In [24]:
arr = np.array(range(25)).reshape((5,5))

arr+5

arr-3

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([[-3, -2, -1,  0,  1],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

### Broadcasting Exponentiation

In [25]:
arr = np.array(range(9)).reshape((3,3))

arr**2

arr**0.5

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

### Broadcasting Floor & Modulo Division

In [26]:
arr = np.array(range(16)).reshape((4,4))

arr//3

arr%3

array([[0, 0, 0, 1],
       [1, 1, 2, 2],
       [2, 3, 3, 3],
       [4, 4, 4, 5]])

array([[0, 1, 2, 0],
       [1, 2, 0, 1],
       [2, 0, 1, 2],
       [0, 1, 2, 0]])

## Module 4.7: Manipulating Arrays: Element-Wise Array Operations

Above, I showed you how you can manipulate arrays through broadcasting, but you can also do element-wise operations with arrays.

These are sometimes different than broadcasting because you can use mathematical operators between arrays of the same shape and size!

There's also some really useful NumPy functions to help:

| Function | Description |
| :---: | --- |
| `maximum()` | Calculates element-wise maximum value between array-array or array-scalar |
| `minimum()` | Calculates element-wise minimum value between array-array or array-scalar |
| `clip()` | Covered above, set's min-max boundaries for an array. Faster than `maximum()` or `minimum()` |
| `sq_rt()` | Takes element-wise square root through array |
| `exp()` | Takes element-wise exponential function $e^x$ |
| `log()` | Takes natural logarithm $\ln{x}$ element-wise, inverse of `exp()` |



### Array-Array Operations with Mathematical Operators

If you use the built-in python operators (+ - * /), they do element-wise operations on arrays! You saw this in broadcasting, but we can also do this element-wise between two arrays of the same shape.

This saves considerable time over using lists, as arrays are compacted into memory and have no references.

*Note: This also works with the rest of the operators (** // %)*

#### Addition and Subtraction Element-Wise

In [28]:
arr = np.array(range(5,10))
arr2 = np.array(range(0,5))

arr+arr2

arr-arr2

array([ 5,  7,  9, 11, 13])

array([5, 5, 5, 5, 5])

#### Multiplication and Division Element-Wise

In [31]:
arr = np.array(range(25)).reshape((5,5))
arr2 = np.array(range(1,26)).reshape((5,5))

arr*arr2

arr/arr2

array([[  0,   2,   6,  12,  20],
       [ 30,  42,  56,  72,  90],
       [110, 132, 156, 182, 210],
       [240, 272, 306, 342, 380],
       [420, 462, 506, 552, 600]])

array([[0.        , 0.5       , 0.66666667, 0.75      , 0.8       ],
       [0.83333333, 0.85714286, 0.875     , 0.88888889, 0.9       ],
       [0.90909091, 0.91666667, 0.92307692, 0.92857143, 0.93333333],
       [0.9375    , 0.94117647, 0.94444444, 0.94736842, 0.95      ],
       [0.95238095, 0.95454545, 0.95652174, 0.95833333, 0.96      ]])

### Application Time: Test Scores CSV

Using what we know above, I'm going to walk you through calculating a student's final grade based upon weights and a grading scale. We're going to use the same CSV as earlier.

As a note, the columns are: HW1, HW2, HW3, Midterm, Final

Homeworks are out of 10, and the exams are out of 100.

Each homework is worth 10% of final grade, midterm 30% and final 40%!

To make math easy, you can make the max score achievable 100 points.

Calculate each students final grade in the following function:

In [42]:
target_url = "https://raw.githubusercontent.com/mhall-simon/sdac-training/main/data/arr-2D-test-scores.csv"

arr = np.genfromtxt(target_url, delimiter=',', skip_header=1)

def final_grade(arr):
    arr[:,3]/=100
    arr[:,4]/=100
    arr[:,3]*=30
    arr[:,4]*=40
    return arr.sum(axis=1)

arr

arr = final_grade(arr)
arr

array([[ 8.,  9.,  5., 89., 96.],
       [ 7.,  5.,  7., 91., 99.],
       [10.,  8.,  4., 77., 87.],
       [ 9.,  7.,  5., 80., 66.],
       [ 5.,  9.,  8., 88., 90.]])

array([87.1, 85.9, 79.9, 71.4, 84.4])

## Module 4.8: Manipulating Arrays: Matrix & Vector Mathematics

1. numpy.dot()
2. numpy.matmul()
3. @ operator
4. 

## Module 4.9: Random Number Generation (RNG)

When programming, we sometimes need to sample random numbers from a distribution. It's very common in Markov Chains and Monte Carlo simulations, and sometimes we need samples to check the edges of a distribution.

Thankfully, NumPy makes this very easy with the built in RNG. (You saw this earlier too!)

If you check out the docs, you'll see that you can sample from over 30 different distributions!

### Step 1: Import RNG & Create RNG Object

In [43]:
from numpy.random import default_rng
rng = default_rng()

### Step 2: Generate Your Samples (Standard Normal Example)

The code below is going to draw 100 samples from a standard normal distribution!

In [45]:
arr = rng.standard_normal(25)
arr

array([-0.36966815, -0.64150371, -0.19127587,  0.87528453, -0.32133509,
       -0.96800824, -0.17910388, -0.41626161,  0.50721487, -0.98142445,
       -1.47155296,  1.47163439, -0.44797422, -0.82641766, -2.5641953 ,
        0.75563002, -0.75029752, -0.42743011, -0.82542057, -0.386396  ,
        1.08949598,  0.26505185, -0.1696318 ,  0.20074065, -1.14404807])